# Generated by Django 3.1.7 on 2021-04-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsAndTours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('address', models.TextField(max_length=1000)),
                ('about', models.TextField(max_length=1000)),
                ('location', models.TextField(max_length=1000)),
            ],
        ),
    ]
