# Generated by Django 3.1.7 on 2021-04-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsandtours',
            name='district',
            field=models.TextField(default='Surendranagar', max_length=100),
        ),
    ]
